name: CD

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  jsr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
    - run: echo "DRY_RUN=--dry-run" >> "$GITHUB_ENV"
      if: github.event_name == 'pull_request'
    - run: deno lint
    - run: deno publish $DRY_RUN # idempotent
