name: Release

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - run: deno lint
      - run: deno test --no-check

      - run: npm install --ignore-scripts
      - run: npm run prepare

      - name: Publish to JSR
        if: github.event_name == 'push'
        run: deno publish --set-version="${GITHUB_REF_NAME/v/}"

      - name: Publish to npm
        if: github.event_name == 'push'
        run: |
          npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
          npm pkg set version="${GITHUB_REF_NAME/v/}"
          npm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_CONFIG_ACCESS: public
